services:
  # Ông 1: Database
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ông 2: App FastAPI của bạn
  web-api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
        - DATABASE_HOST=db
      # - DATABASE_URL=postgresql://admin:password123@db:5432/fastapi_db
        - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && 
         alembic upgrade head && 
         gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  # Ông 3: Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    # Lệnh chạy tunnel dùng file config trong folder cloudflare
    command: tunnel --url http://web-api:8000
    # volumes:
    #   - ./cloudflare:/etc/cloudflared
    depends_on:
      - web-api

volumes:
  postgres_data:
