"""auto create nickname

Revision ID: 8289f49f874b
Revises: c1f71aaa4d83
Create Date: 2026-03-12 14:48:38.190568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8289f49f874b'
down_revision: Union[str, Sequence[str], None] = 'c1f71aaa4d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with a server default so existing rows can be backfilled.
    op.add_column(
        'users',
        sa.Column(
            'nickname',
            sa.String(length=50),
            nullable=False,
            server_default='',
        ),
    )

    # Remove the server default once existing rows are populated.
    op.alter_column('users', 'nickname', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
